[package]
name = "matrix-system"
version = "0.1.0"
description = "Created with Anchor"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "matrix_system"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = []

[dependencies]
anchor-lang = "0.31.0"
anchor-spl = "0.31.0"
spl-token = "=5.0.0"
chainlink_solana = "1.0.0"
solana-security-txt = "1.1.1"
default-env = "0.1.1"
spl-associated-token-account = "=3.0.2"

[patch.crates-io]
solana-program = { version = "=2.1.0" }
solana-zk-sdk = { version = "=2.1.0" }